### ISSUE TITLE
App fails to login to profile on macOS Big Sur

### ISSUE THREAD

**Issue by christopherkeil0689** [otto-de/logsmith#11]
Logsmith currently fails on macOS Big Sur (11.0.1) when trying to select a profile. Before the "Mfa Token" modal dialog opens, the application hangs and becomes unresponsive.

The system logs notably display the following error, repeatedly with multiple retries:

`Failed to copy signing info for 42584, responsible for file:///Applications/logsmith.app/Contents/MacOS/logsmith: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)" `
[bigsur_error.txt](https://github.com/otto-de/logsmith/files/5545279/bigsur_error.txt)

**Comment by jensschaa3653** [comment]
It seems that Qt has issues with the new mac os version, as seen here:
https://bugreports.qt.io/browse/QTBUG-86358?jql=text%20~%20%22big%20sur%22%20ORDER%20BY%20priority%20DESC%2C%20cf%5B10184%5D%20ASC

We tried downgrading but it did not help. Seems like we have to wait for a new release of pyqt
