### ISSUE TITLE
logsmith cli is not exiting the terminal

### ISSUE THREAD

**Issue by ewoelfel** [otto-de/logsmith#14]
After logging into a new profile using
`logsmith --login some-profile` the cli is not releasing the terminal again.

One has to use the timeout command right now to release the terminal currently, like that:
`timeout 10 logsmith --login some-profile` 

Tested on a Manjaro Linux machine
Logsmith version: logsmith 6.0.0

**Comment by TomVollerthun1337** [comment]
This should be fixed by https://github.com/otto-de/logsmith/pull/13

**Comment by TomVollerthun1337** [comment]
Can you please check if running 
`logsmith --login some-profile --oneshot`
with version 6.1 works as you'd expect?

**Comment by ewoelfel** [comment]
Thank you! It works like a charm on a Manjaro linux.
